### ISSUE TITLE
Hello, you are updating the TWRP s7 version ?

### ISSUE THREAD

**Issue by NoRRt** [ananjaser1211/Helios_8890#4]
https://dl.twrp.me/herolte/
https://dl.twrp.me/hero2lte/

twrp-3.6.2_9-0-herolte.img.tar |  2022-06-01 

twrp-3.6.2_9-0-hero2lte.img.tar |  2022-06-01

**Comment by ananjaser1211** [comment]
I am not the official maintainer of TWRP for HERO, i host my own version here https://github.com/ananjaser1211/android_device_samsung_hero

which is at version 3.4
